version: '3.1'

services:
  api:
    # reminder, don't use latest tag in production, use versions created by CI/CD
    image: aidengaripoli/alpha-api:$VERSION
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
      - JWT_SECRET=$JWT_SECRET
      - DB_HOST=database
      - DB_NAME=alpha
    deploy:
      replicas: 2

  database:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    volumes:
      - database-data:/data/db
    ports:
      - "$MONGO_PUBLIC_PORT:27017"

volumes:
    database-data:
