version: '3.1'

services:
  api:
    build:
      context: .
      args:
        - NODE_ENV=development
    command: nodemon --inspect=0.0.0.0:9229
    ports:
      - "80:3000"
      - "9229:9229"
      - "9230:9230"
    volumes:
      - .:/opt/app:delegated
      - ./package.json:/opt/package.json
      - ./package-lock.json:/opt/package-lock.json
      - notused:/opt/app/node_modules
    environment:
      - NODE_ENV=development
      - JWT_SECRET=secret
      - DB_USER=node
      - DB_PASS=secret
      - DB_HOST=database
      - DB_NAME=alpha
      - DB_PORT=27017
    depends_on:
      - database
    user: root

  database:
    image: mongo
    restart: always
    environment:
    - MONGO_INITDB_ROOT_USERNAME=mongoadmin
    - MONGO_INITDB_ROOT_PASSWORD=adminpass
    - MONGO_INITDB_DATABASE=alpha
    volumes:
      - database-data:/data/db
      - ./database_init.sh:/docker-entrypoint-initdb.d/database_init.sh
    ports:
      - "27017:27017"

volumes:
    notused:
    database-data:
