version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: |
          docker-compose -f docker-compose.test.yml -p ci build
          docker-compose -f docker-compose.test.yml -p ci up --abort-on-container-exit
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$TAG .
          docker push $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$TAG
